const EVENT_TYPES = Object.freeze([
  'TEST_EVENT',
  'DEVICE_REGISTERED',
  'LOCATION_UPDATE',
  'LOCATION_VERIFIED',
  'LOCATION_ANOMALY',
  'SIM_REPLACEMENT',
  'DEVICE_CHANGED',
  'NEW_RECIPIENT',
  'LARGE_TRANSACTION',
  'TRANSACTION_ATTEMPT',
  'SECURITY_CHANGE',
]);

const EVENT_TYPE_SET = new Set(EVENT_TYPES);

module.exports = { EVENT_TYPES, EVENT_TYPE_SET };
